### ISSUE TITLE
Unable to generate commit message for staged changes

### ISSUE THREAD

**Issue by myoss** [kevin-kidd/aicommit#2]
<img width="429" alt="image" src="https://github.com/user-attachments/assets/62f9f894-2195-4729-9fd6-2a16237f1dce">

## Current Behavior
The system is not able to generate git commit messages for files that are in the staged changes area.

## Expected Behavior
Should be able to analyze staged files and generate appropriate commit messages based on the changes.

## Possible Solution
Need to implement functionality to:
1. Read staged files list using git commands
2. Parse the changes in staged files
3. Generate commit message based on the analyzed changes

**Comment by kevin-kidd** [comment]
Thanks for opening the issue. Could you please confirm if you are using the latest version of the vs code extension? I pushed an update earlier today to fix a bug related to this.

**Comment by myoss** [comment]
Issue resolved, but discovered a new concern.

## Current Status
✅ Generation of commit messages for staged changes is now supported

## New Issue
Currently, commit messages are generated separately for each file, which leads to:
1. Unable to generate a unified, contextual commit message for multiple related file changes
2. When multiple files belong to the same feature change, commit messages become fragmented
3. Lacks understanding of the overall change context

## Suggested Improvements
Consider optimizing the algorithm to:
- Analyze changes across all staged files
- Understand relationships between file changes
- Generate a unified commit message that summarizes all related changes

Would you like me to create a new issue for tracking this new behavior?
