### ISSUE TITLE
 Error generating commit messages: 404 "404 not found."

### ISSUE THREAD

**Issue by yidasanqian** [kevin-kidd/aicommit#3]
API key test failed for provider undefined and model undefined: Provider is not set. Please configure it in the settings.

![image](https://github.com/user-attachments/assets/eb6a431e-d144-408d-92bc-39dfa733c943)

**Comment by yidasanqian** [comment]
![image](https://github.com/user-attachments/assets/62779be1-a06b-407a-86ba-62def2dcbcd5)

**Comment by kevin-kidd** [comment]
Thank you for reporting this bug. I have published version 0.0.7 which should resolve this issue. Please let me know if your issue persists after updating to the latest version.

**Comment by yidasanqian** [comment]
> Thank you for reporting this bug. I have published version 0.0.7 which should resolve this issue. Please let me know if your issue persists after updating to the latest version.

Resolved. Hope to support Azure OpenAI interface.

**Comment by kevin-kidd** [comment]
Great. I will be adding Azure OpenAI support in the next couple weeks.
