### ISSUE TITLE
[Enhancement] Generate consolidated commit messages across multiple files

### ISSUE THREAD

**Issue by myoss** [kevin-kidd/aicommit#4]
## Currently
commit messages are generated separately for each file, which leads to:
1. Unable to generate a unified, contextual commit message for multiple related file changes
2. When multiple files belong to the same feature change, commit messages become fragmented
3. Lacks understanding of the overall change context

## Suggested Improvements
Consider optimizing the algorithm to:
- Analyze changes across all staged files
- Understand relationships between file changes
- Generate a unified commit message that summarizes all related changes

**Comment by kevin-kidd** [comment]
Thank you for opening this issue. The analysis and understanding of the relationship between changed files will largely depend on the model, prompt and context. In my tests, I have found that some models perform better at encapsulating the relationship between changes across multiple staged files, while others struggle. I have added some extra guidelines in the default prompt to emphasize the importance of including all the changes when generating each commit message. Soon I will be adding a prompt template system and commit message style options which will allow users to have more control over the quality and style of the generated commit messages.

I will be adding these 2 features in the coming weeks. In the mean time, if you have any other feature suggestions or prompt improvements to improve the quality of generated commit messages, please feel free to open another issue or PR with those suggestions and I will add them.
